
/*
============================
    Problem #2
    Even Fibonacci numbers
============================


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

/*
See with console at repl.it
https://repl.it/Eyrq/1
*/

var fNums = [];
var a = 0;
var max = 10;
var sum = 0;



fNums.push(1);
fNums.push(2);

do {
  var lastNumIndex = fNums.length - 1;
  var last2NumIndex = lastNumIndex - 1;

  var nextNum = fNums[lastNumIndex] + fNums[last2NumIndex];
  fNums.push(nextNum);

  a++;
}
while(a < max);


console.log('Fibonacci Numbers: ' + fNums);


for(var b=0; b < fNums.length; b++) {
  if(fNums[b] % 2 === 0) {
    sum += fNums[b];
  }
}


console.log('Sum of even numbers in above array :' + sum)
